config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root "site#home"
  post "/users/:id" => "users#updatecharity"
  resources :charities
  resources :users
  resources :games

  scope "/api" do
    resources :game_sessions, only: [:create, :destroy]
  end

end

app/models/charity.rb
class Charity < ActiveRecord::Base
	has_many :users, through: :UserCharities
	has_many :users, through: :donations
end

app/models/donation.rb
class Donation < ActiveRecord::Base
  belongs_to :user
  belongs_to :charity
  
end

app/models/game.rb
class Game < ActiveRecord::Base
	has_many :users, through: :GamerProfile
	mount_uploader :game_image, GameImageUploader
end

app/models/game_session.rb
class GameSession < ActiveRecord::Base
  belongs_to :gamer_profile
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :games, through: :gamerProfile
  has_many :charities, through: :userCharities
  has_many :charities, through: :donations
  has_many :donations
  has_many :gameSessions
end

app/models/user_charity.rb
class UserCharity < ActiveRecord::Base
  belongs_to :user
  belongs_to :charity
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end

   def admin_only
    unless current_user && current_user.role == 'adminGamer'
      redirect_to "/"
    end        
  end

  def after_sign_in_path_for(resource)
    charities_path
  end

  #   def after_sign_in_path_for(resource)
  #   sign_in_url = new_user_session_url
  #   if request.referer == sign_in_url
  #     super
  #   else
  #     stored_location_for(resource) || request.referer || root_path
  #   end
  # end
# end
end

app/controllers/charities_controller.rb
class CharitiesController < ApplicationController

	def index
		@user = current_user
		@charities = Charity.all
	end
end

app/controllers/game_sessions_controller.rb
class GameSessionsController < ApplicationController
	def create
		user = current_user
		gameSession = GameSession.create(session_params)
		user.score = user.score + gameSession.score
		if gameSession.score >= user.highscore
			user.highscore = gameSession.score
		end
		user.save
		render json: gameSession
	end

	def destroy
	end

	private

	def session_params
		params.require(:game_session).permit(:user_id, :score)
	end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
	before_action :authenticate_user!
	before_action :admin_only, only: [:new, :create]
	def new
		@game = Game.new
		@game.game_image = params[:file] 
	end

	def create
		game = Game.new(game_params)

		if game.save
			redirect_to games_path
		else
			render "index"
		end
	end

	def index
		@games = Game.all
	end

	def show
		@game = Game.find_by(id: params[:id])
		if current_user.charities
			render "show"
		else
			redirect_to charities_path
		end
	end

	private

	def game_params
		params.require(:game).permit(:name, :game_image, :description, :time)
	end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController

def home

end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
	end

	def create
	end

	def updatecharity
		user_charity = Charity.find_by(name: params[:charity])
		puts user_charity.inspect
		if current_user.charities.find_by(name: user_charity.name)
			current_user.current_charity = user_charity.name
			current_user.save!
			redirect_to user_path(current_user)
		else
			puts "not found *****************"
			current_user.charities << user_charity
			current_user.current_charity = user_charity.name
			current_user.save!
			puts current_user.current_charity
			puts current_user.charities.inspect
			redirect_to user_path(current_user)
		end
		
	end

	def show
		@user = current_user
		@current_charity = current_user.current_charity
		puts current_user.inspect
		render "profile"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charities_helper.rb
module CharitiesHelper
end

app/helpers/game_sessions_helper.rb
module GameSessionsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/charities/index.html.erb
<div class="container">
	<div class="row">
		<div class="col s7 push-s2">

		<div class="center">
			<h3>Select a charity:</h3>
      <p class="red-text">**Please see disclaimer below**</p>
		</div>
		<br>
		<br>
			<%= form_tag(@user, class:"change-charities-form", method: "post", action:"update", controller:"user") do%>
				<% @charities.each do |charity| %>
					<%= radio_button_tag :charity, charity.name, id: charity.id %>
					<%=label_tag "charity_#{charity.name}", charity.name%>
					<hr>
					<br>
					<% end %>
					<br>
					<%= submit_tag "Submit", class: "login-button btn" %>
					<% end  %>

		</div>
	</div>

  <div class="row">
    <div class="col s12">
      <p class="red-text center">**These are not real charities. This is just a demo/model. The names above are only for educational purposes, this site and company does not actually contribute to these charities. **</p>
    </div>
  </div>


	<div class="row">
        <div class="col l4">
          <div class="card small">
            <div class="card-image">
            <%= image_tag "hfot.png" %>
              <!-- <span class="card-title"><span class="black">Homes For Our Super Troops</span></span> -->
            </div>
            <div class="card-content black-text">
              <p>Homes for Our Troops** is a nonprofit organization building specially adapted, mortgage-free homes for Vets.</p>
            </div>
          </div>
          </div>

		<div class="col l4">	
          <div class="card small">
            <div class="card-image">
            <%= image_tag "Adoptions.png" %>
              <!-- <span class="card-title"><span class="black">Humane Society</span></span> -->
            </div>
            <div class="card-content black-text">
              <p>The Humane Society of the United States** is the nation’s largest and most effective animal protection organization.</p>
            </div>
          </div>
        </div>

		<div class="col l4">
          <div class="card small">
            <div class="card-image">
	            <%= image_tag "uncf.jpg" %>
              <!-- <span class="card-title"><span class="black">UNCF (United Negro College Fund)</span></span> -->
            </div>
            <div class="card-content black-text">
              <p>UNCF**  (United Negro College Fund) is the nation's largest and most effective minority education organization. </p>
            </div>
          </div>
        </div>
      </div>
</div>

app/views/games/index.html.erb
<div class="container">
	<div class="row">

			<% @games.each do |game|%>
		<div class="col s6 l6 ">
    <% if game.id == 1 %>
			<a href="/games/<%=game.id%>">	
			<div class="card large black-text">
            <div class="card-image">
            <%= image_tag "spaceAdInvaders.jpg", size:"400x300" if game.name== "Space Ad Invaders" %>
            <%= image_tag "pacMan.gif", size:"400x300" if game.name== "Pac Ad Man" %>
              <% if game.game_image.nil? %>
              <img src="images/sample-1.jpg">
              <%end %>
              <span class="card-title"> <%=game.name %></span>
            </div>
            <div class="card-content black-text">
              <p> <%= game.description %></p>
            </div>
            <div class="blue-text card-action">
              Play: <%= game.name %>
	          <%# if current_user.role == "adminGamer" %>
          	  <%#= link_to("Edit", edit_game_path(game)) %>
          	  <%# end %>
            </div>
          </div>
          </a>
          <% else %>

        <div class="card large black-text">
            <div class="card-image">
            <%= image_tag "spaceAdInvaders.jpg", size:"400x300" if game.name== "Space Ad Invaders" %>
            <%= image_tag "pacMan.gif", size:"400x300" if game.name== "Pac Ad Man" %>
              <% if game.game_image.nil? %>
              <img src="images/tile.jpeg">
              <%end %>
              <span class="card-title"> <%=game.name %></span>
            </div>
            <div class="card-content black-text">
              <p> <%= game.description %></p>
            </div>
            <div class="card-action">
              Play: <%= game.name %>
            <% if current_user.role == "adminGamer" %>
              <%= link_to("Edit", edit_game_path(game)) %>
              <% end %>
            </div>
          </div>

          <% end %>

		</div>
          <% end %>

	</div>
</div>

app/views/games/new.html.erb
 <div class="container">
      <div class="row">
        <div class="col s6">
        <h4>Create a game</h4>
        	<%= form_for [@game] do |f| %>

			<%= f.label :name, "Name" %>
			<%= f.text_field :name, :class => "validate" %>
        </div>
    </div>
    <div class="row">
        <div class="col s6">
        	<%=f.label :game_image %>
  			<br>
    			<%= f.file_field :game_image %>
        </div>
    </div>

      <div class="row">
        <div class="col s8">
         	<%= f.label :description%>
			<%= f.text_area :description %>
        </div>
      </div>

      <div class="row">
        <div class="col s8">
          <%= f.label :time %>
          <%= f.text_field :time %>
        </div>
      </div>

      <div class="row">
      	<div class="col s3">
      		<%= f.submit "Submit" %>
      		<% end %>
      	</div>
      </div>
  </div>

app/views/games/show.html.erb
<div class="container">
	<div class="row">
		<div class="welcome-text">
			<h3>Welcome to <%= @game.name %>! Time to play.</h3>
			<h5>What are you doing? <%=@game.description %></h5>
		</div>
	</div>
</div>
<div class="col 212 ">
			<div class="points-holder left-align" data-game-id="<%=@game.id%>" data-user-id="<%= current_user.id%>"><h4 class="red-text black">Points: <span class="points">0</span></h4></div>
			<div id="<%=@game.name[0..4] %>" class="valign-wrapper">
				<div class="valign start-holder center-align">
					<a href="#" class="start-game light-green-text text-accent-4">Start Game</a>
				</div>
			</div>
</div>

<div class="col s12">
	<div>
		<h4 class="instructions">Instructions:</h4>

		<p class=" instructions-text">
			Press <i class="material-icons">keyboard_arrow_left</i> ARROWS <i class="material-icons">keyboard_arrow_right</i> to move left and right. Press SPACEBAR <i class="material-icons">space_bar</i> to shoot. Dodge the red bullets and shoot the alien ads!
		</p>
		<div class="center">
			<a href="javascript:window.location.href=window.location.href" class="waves-effect waves-light btn-large red">Replay!</a>
			
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GC</title>

  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/css/materialize.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--Import Google Icon Font-->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href='https://fonts.googleapis.com/css?family=ABeeZee|Black+Ops+One' rel='stylesheet' type='text/css'>
</head>
<body>
  <header>
    <div class="navbar-fixed">
    <nav>
        <div class="nav-wrapper default-nav-bar">
       <!--    <div class="container"> -->
            <a href="/" class="brand-icon"><%= image_tag "g2charityLogoPurple.png", class: "g2charityLogo" %></a>
            <%=link_to("GAMING TO THE CHARITY", root_path, class:"brand-logo") %>
            
          <!-- </div> -->
          <ul id="nav-mobile" class="right">
            <li><%= link_to("Games", games_path, class: "white-text") %></li>
            <% if user_signed_in? %>
            <li>
                <% if current_user.charities.blank? %>
                <span class="white-text">Pick a Charity!</span>
                <% else %>
                <span class="white-text">Current charity: <span class="charity-name"><%=current_user.current_charity%></span></span>
                <% end %>
            </li>
            <li>
            <%= link_to("Profile", user_path(current_user), class: "white-text") %>
            </li>
            <li>
            <%= link_to("Select a Charity", charities_path, class: "white-text") %>
            </li>
            <li>
            <%= link_to("Sign out", destroy_user_session_path, method: :delete, class: "white-text") %>
            </li>
            <% else %>
            <li>
              <%= link_to("Login", new_user_session_path, class: "white-text") %>
            </li>
            <li>
            <%= link_to("Sign Up", new_user_registration_path, class: "white-text") %>
            </li>
            <% end %>
          </ul>
        </div>
    </nav>
    </div>
  </header>
<main>
  <%= yield %>
  
</main>

<footer class="page-footer white-text">
          <div class="container ">
            <div class="row">
              <div class="col l6 s6">
                <h6 class="white-text gc-logo"> 
                  <span>
                    <%= image_tag "g2charityLogoPurple.png", class: "g2charityLogo" %>
                    
                  </span>
                  Gaming to the Charity
                </h6>
                <p class="white-text">Made with the spirit of coding and gaming.</p>
              </div>
              <div class="col l4 offset-l2 s4 offset-s2">
                <h5 class="white-text">Navigation</h5>
                <ul>
                  <li>
                      <%=link_to("Home", root_path, class:"white-text") %>
                  </li>
                  <li>
                      <%= link_to("Games", games_path, class: "white-text") %>
                  </li>
                  <% if current_user %>
                  <li>
                      <%= link_to("Sign out", destroy_user_session_path, method: :delete, class: "white-text") %>
                  </li>
                  <% else %>
                  <li>
                     <%= link_to("Login", new_user_session_path, class: "white-text") %>
                  </li>
                  <li>
                    <%= link_to("Sign Up", new_user_registration_path, class: "white-text") %> 
                  </li>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container white-text">
            © 2016 Copyright 
            </div>
          </div>
</footer>

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.min.js"></script>
</body>
</html>

app/views/site/home.html.erb
<div class="container home-aboutus">
	<div class="section">
		<div class="row home-row">
			<div class="col push-s2 s8 center">
				<h4>A Little About Us...</h4>
				<p class="left-align light ">This company is about giving back. The reason I made this app was to allow people to give back without taking money from them. Instead, spend some time sitting at a computer doing good for the world. There is so much we can do at our fingertips, here is another way to feel a little better and game your heart out. There are so many platforms to game, and while they are fun, they don't give you the opportunity to game and give. Here at Game For Charity you can give back and play. Login or Sign Up to join in the fun of playing and gaming!</p>
			</div>
		</div>
	</div>
</div>

app/views/users/profile.html.erb
<div class="container profile-holder">
	<div class="row">
		<div class="col s3">
			<%= image_tag "one.jpg", alt: "Cool image Here", class: "cool-avatar" %>
		</div>
		<div class="col s8">
			
			<div class="row">
				<div class="col s12">
					<h4 class="profile-name">
						<strong>
						<%= @user.name%>
						</strong>
					</h4>
					<div>
						<h6>
							Total Points: <%=@user.score %> <br><br> Highscore: <%=@user.highscore %>
						</h6>				
					</div>
					<br>
					<hr>
				</div>
			</div>

			<div class="row">
				<div class="col s12">
					<h5>
						Charities Helped:
					</h5>
					<ul>
						<% @user.charities.each_with_index do |charity, i|%>

						<% if charity.name? && charity.name === @user.current_charity %>
						<li>
							<p>
							You are currently helping: <%= charity.name %>
							</p>
						</li>
						<% elsif charity.name? %>
						<li>
							<p>
								<%= charity.name %>
							</p>
						</li>
						<% else %>
						<li>
							<a href="/charities">Need to pick a Charity? Click Here.</a>
						</li>
						<% end %>
						<% end %>
					</ul>
				</div>
			</div>
		</div>
	</div>
	
</div>